name: Node.js Windows-api

on:
   push:
      branches: ['main']
   pull_request:
      branches: ['main']

jobs:
   build:
      runs-on: self-hosted

      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js 16.x
           uses: actions/setup-node@v2
           with:
              node-version: 16.x
         - run: npm install
         - run: npm test
         - name: Load environment variables
           env:
              ENV_FILE: ${{ github.workspace }}\.env
           run: |
              Write-Host "Loading environment variables from $ENV_FILE"
              if (Test-Path $ENV_FILE) {
                  Get-Content $ENV_FILE | ForEach-Object { [System.Environment]::SetEnvironmentVariable($_.Split('=')[0], $_.Split('=')[1], [System.EnvironmentVariableTarget]::Process) }
              }
              else {
                  Write-Host "Environment file not found: $ENV_FILE"
              }
         - run: pm2 restart windowsApi
         #  - run: npm install -g pm2
         #  - run: pm2 start ./startscript.js --name windowsApi
         #  - run: chmod 777 ./pm2_runner.sh
         #  - run: bash ./pm2_runner.sh
         #  - run: "& 'C:\\Program Files\\nodejs\\pm2.ps1' restart windowsApi"
